# Generated by Django 4.0.4 on 2022-04-19 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passwords', '0002_remove_password_other_users_viewpassword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.BooleanField(default=False)),
                ('edit', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passwords.password')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='viewpassword',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='viewpassword',
            name='password',
        ),
        migrations.RemoveField(
            model_name='viewpassword',
            name='user',
        ),
        migrations.DeleteModel(
            name='EditPassword',
        ),
        migrations.DeleteModel(
            name='ViewPassword',
        ),
    ]
